---

- name: Looking up user home
  shell: >
    egrep "^{{ pm2_user }}:" /etc/passwd | awk -F: '{ print $6 }'
  changed_when: false
  register: pm2_user_home

- name: Installing startup script
  command: "pm2 startup {{ pm2_platform }} -u {{ pm2_user }} --hp {{ pm2_user_home.stdout }}"
  when: pm2_upstart

- name: Configuring service
  service:
    name: "{{ pm2_service_name }}"
    state: "{{ pm2_service_state }}"
    enabled: "{{ pm2_service_enabled }}"
  when: pm2_upstart
