---
dependencies: []

galaxy_info:
  author: tyson
  description: NVM installation for Linux
  company: "VMO Holdings"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
      - 6
      - 7
    - name: Debian
      versions:
      - all
    - name: Ubuntu
      versions:
      - precise
      - raring
      - saucy
      - trusty
      - xenial
  galaxy_tags:
    - development
    - web
    - nvm
    - node version manager
    - nodejs
    - node
    - javascript
