---
dependencies: []

galaxy_info:
  role_name: swap
  author: Tyson
  description: Swap file and swap management for Linux.
  company: "VMO Holdings"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - system
    - server
    - swap
    - swapfile
    - pagefile
    - performance
    - memory
    - ram
